// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzKxAjS-f_y9ZbeaUMaUbZDKymyQW2RD8',
    appId: '1:704893967393:web:74d0c6ae6e954f0dde9760',
    messagingSenderId: '704893967393',
    projectId: 'ltldriver',
    authDomain: 'ltldriver.firebaseapp.com',
    storageBucket: 'ltldriver.appspot.com',
    measurementId: 'G-LRHGW6ZQJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaoZ3MyqxI9CN0LxcVJRbRW_smSpHz1rs',
    appId: '1:704893967393:android:f9782f6f7960a1f8de9760',
    messagingSenderId: '704893967393',
    projectId: 'ltldriver',
    storageBucket: 'ltldriver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7cL5GVpLCEI4mY4VVxPMVm20egtg5X0Q',
    appId: '1:704893967393:ios:0cb0d88997c2bb63de9760',
    messagingSenderId: '704893967393',
    projectId: 'ltldriver',
    storageBucket: 'ltldriver.appspot.com',
    iosBundleId: 'com.ltldriver.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7cL5GVpLCEI4mY4VVxPMVm20egtg5X0Q',
    appId: '1:704893967393:ios:b7cfced1667d54f9de9760',
    messagingSenderId: '704893967393',
    projectId: 'ltldriver',
    storageBucket: 'ltldriver.appspot.com',
    iosBundleId: 'com.example.opentrip.RunnerTests',
  );
}
